src/Entity/Maison.php
<?php

namespace App\Entity;

use App\Repository\MaisonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


/**
 * @ORM\Entity(repositoryClass=MaisonRepository::class)
 */
class Maison
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     *  @Assert\NotBlank(message=" nomimmob doit etre non vide")
     * @ORM\Column(type="string", length=255)
     */
    private $nomimmob;

    /**
     * @Assert\NotBlank(message=" nom du loyé doit etre non vide")
     * @ORM\Column(type="string", length=255)
     */
    private $nom_loy;

    /**
     * @Assert\NotBlank(message=" cin doit etre non vide")
     * @Assert\Length(
     *                 min= 8,
     *                 max= 8,
     *                 minMessage="8 chiffres recommandés",
     *                 maxMessage="8 chiffres recommandés" )
     * @ORM\Column(type="string", length=8)
     */
    private $cin_loy;

    /**
     * @Assert\NotBlank(message=" tel doit etre non vide")
     * @Assert\Length(
     *                 min= 8,
     *                 max= 8,
     *                 minMessage="8 chiffres recommandés",
     *                 maxMessage="8 chiffres recommandés" )
     * 
     * @ORM\Column(type="string", length=8)
     */
    private $numerotel;


    

    /**
     *  
     * @ORM\Column(type="date")
     */
    private $fin;

    /**
     * @ORM\Column(type="date")
     */
    private $deb;

    /**
     * @ORM\Column(type="integer")
     */
    private $prix;










    public function __construct()
    {
        $this->payements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomImmob(): ?string
    {
        return $this->nomimmob;
    }

    public function setNomImmob(string $nomimmob): self
    {
        $this->nomimmob = $nomimmob;

        return $this;
    }

    public function getNomLoy(): ?string
    {
        return $this->nom_loy;
    }

    public function setNomLoy(string $nom_loy): self
    {
        $this->nom_loy = $nom_loy;

        return $this;
    }

    public function getCinLoy(): ?string
    {
        return $this->cin_loy;
    }

    public function setCinLoy(string $cin_loy): self
    {
        $this->cin_loy = $cin_loy;

        return $this;
    }
    public function getNumeroTel(): ?string
    {
        return $this->numerotel;
    }

    public function setNumeroTel(string $numerotel): self
    {
        $this->numerotel = $numerotel;

        return $this;
    }

    public function __toString()
    {
        return $this->nomimmob;
    }



    /**
     * @return Collection<int, Payement>
     */
    public function getPayements(): Collection
    {
        return $this->payements;
    }

    public function addPayement(Payement $payement): self
    {
        if (!$this->payements->contains($payement)) {
            $this->payements[] = $payement;
            $payement->setMaison($this);
        }

        return $this;
    }

    public function removePayement(Payement $payement): self
    {
        if ($this->payements->removeElement($payement)) {
            // set the owning side to null (unless already changed)
            if ($payement->getMaison() === $this) {
                $payement->setMaison(null);
            }
        }

        return $this;
    }

    public function getFin(): ?\DateTimeInterface
    {
        return $this->fin;
    }

    public function setFin(\DateTimeInterface $fin): self
    {
        $this->fin = $fin;

        return $this;
    }

    public function getDeb(): ?\DateTimeInterface
    {
        return $this->deb;
    }

    public function setDeb(\DateTimeInterface $deb): self
    {
        $this->deb = $deb;

        return $this;
    }

    public function getPrix(): ?int
    {
        return $this->prix;
    }

    public function setPrix(int $prix): self
    {
        $this->prix = $prix;

        return $this;
    }
}

src/Form/MaisonType.php
<?php

namespace App\Form;

use App\Entity\Maison;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class MaisonType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nomimmob')
            ->add('nom_loy')
            ->add('cin_loy')
            ->add('numero_tel')
            ->add('prix')
            ->add('deb')
            ->add('fin');
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Maison::class,
        ]);
    }
}

src/Controller/MaisonController.php
<?php

namespace App\Controller;

use App\Entity\Maison;
use App\Entity\Payement;
use App\Form\MaisonType;
use App\Form\PayementType;
use App\Repository\MaisonRepository;
use App\Repository\PayementRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use MercurySeries\FlashyBundle\FlashyNotifier;


/**
 * @Route("/maison")
 */
class MaisonController extends AbstractController
{

    /**
     * @Route("/", name="app_maison_index", methods={"GET"})
     */
    public function index(MaisonRepository $maisonRepository): Response
    {
        $maison = $maisonRepository->findAll();
        $nbrprest = 0.0;
        foreach ($maison as $maison) {

            $nbrprest += 1;
        }

        $maison = $maisonRepository->findAll();

        $gain = 0;
        foreach ($maison as $maison) {
            $gain += $maison->getPrix() * 12;
        }
        return $this->render('maison/index.html.twig', [
            'maisons' => $maisonRepository->findAll(), 'nbrprest' => $nbrprest, 'gain' => $gain
        ]);
    }

    /**
     * @Route("/new", name="app_maison_new", methods={"GET", "POST"})
     */
    public function new(Request $request, MaisonRepository $maisonRepository, FlashyNotifier $flashy): Response
    {
        $maison = new Maison();
        $form = $this->createForm(MaisonType::class, $maison);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $maisonRepository->add($maison, true);
            $flashy->success('immobilier Crée avec succée!', '#');

            return $this->redirectToRoute('app_maison_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('maison/new.html.twig', [
            'maison' => $maison,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_maison_show", methods={"GET"})
     */
    public function show(Maison $maison): Response
    {
        return $this->render('maison/show.html.twig', [
            'maison' => $maison,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="app_maison_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Maison $maison, MaisonRepository $maisonRepository, FlashyNotifier $flashy): Response
    {
        $form = $this->createForm(MaisonType::class, $maison);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $maisonRepository->add($maison, true);
            $flashy->muted('immobilier modifié avec succée!', '#');
            return $this->redirectToRoute('app_maison_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('maison/edit.html.twig', [
            'maison' => $maison,
            'form' => $form,
        ]);
    }

    /**
     * @Route("/{id}", name="app_maison_delete", methods={"POST"})
     */
    public function delete(Request $request, Maison $maison, MaisonRepository $maisonRepository, FlashyNotifier $flashy): Response
    {
        if ($this->isCsrfTokenValid('delete' . $maison->getId(), $request->request->get('_token'))) {
            $maisonRepository->remove($maison, true);
        }
        $flashy->error('immobilier supprimé avec succée!', '#');
        return $this->redirectToRoute('app_maison_index', [], Response::HTTP_SEE_OTHER);
    }
    /**
     * @Route("/payement/{id}", name="app_postcom")
     */

    public function PackItem(Request $request, MaisonRepository $maisonRepository, $id, PayementRepository $payementRepository): Response
    {
        $maison = $maisonRepository->find($id);
        $payement = $payementRepository->getPostcom($id);

        $nbrprest = 0.0;
        foreach ($payement as $payement) {

            $nbrprest += 1;
        }



        $payement = $payementRepository->getPostcom($id);
        $a = 0;
        foreach ($payement as $payement) {
            if ($payement->getPaye() == "payé")
                $a += 1;
        }



        $payement = $payementRepository->getPostcom($id);
        return $this->render('maison/packItem.html.twig', [

            'maison' => $maison,
            'payements' => $payement,
            'nbrprest' => $nbrprest,
            'a' => $a,



        ]);
    }
    /**
     * @Route("/payement/{id}/new", name="app_postcom1", methods={"GET", "POST"}, requirements={"id":"\d+"})
     */

    public function PackItem1(Request $request, FlashyNotifier $flashy, MaisonRepository $maisonRepository, $id, PayementRepository $payementRepository): Response
    {
        $maison = $maisonRepository->find($id);
        $payement = $payementRepository->getPostcom($id);


        $newPayement = new Payement();
        $form = $this->createForm(PayementType::class, $newPayement);

        $form->handleRequest($request);
        $newPayement->setMaison($maison);
        if ($form->isSubmitted() && $form->isValid()) {

            $payementRepository->add($newPayement, true);
            $newPayement->setMaison($maison);
            $flashy->success('payement Crée avec succée!', '#');
            return $this->redirectToRoute('app_postcom', [
                'id' => $maison->getId()
            ], Response::HTTP_SEE_OTHER);
        }

        return $this->render('maison/new1.html.twig', [

            'maison' => $maison,
            'payements' => $payement,

            'form' => $form->createView(),
        ]);
    }
    
}

templates/maison/_delete_form.html.twig
{% block stylesheet %}
<link rel="stylesheet" href={{asset("nicepage.css")}} media="screen">
<link rel="stylesheet" href={{asset("Accueil.css")}} media="screen">
{% endblock %}
    
    {% block javascript %}
<script class="u-script" type="text/javascript" src={{asset("jquery.js")}} defer=""></script>
    <script class="u-script" type="text/javascript" src={{asset("nicepage.js")}} defer=""></script>
    {% endblock %}
<form method="post" action="{{ path('app_maison_delete', {'id': maison.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ maison.id) }}">
    
    <button class="u-border-2 u-border-palette-2-base u-btn u-btn-round u-button-style u-hover-palette-2-base u-none u-radius-6 u-text-hover-white u-btn-2">SUPPRIMER</button>
</form>

templates/maison/_form.html.twig
{{ form_start(form,{attr:{novalidate:'novalidate'}}) }}
    {{ form_widget(form) }}
    {{ form_errors(form) }}
    <br>
    
    <center><button class="btn" style="background-color:gray;border-color: black;color: white">{{ button_label|default('enregistrer') }}</button></center>
{{ form_end(form) }}

templates/maison/edit.html.twig
{% extends 'front.html.twig' %}

{% block title %}Edit Maison{% endblock %}

{% block body %}
<section class="u-clearfix u-palette-2-base u-section-3" id="carousel_38bf">
    <h1>Edit Maison</h1>

    {{ include('maison/_form.html.twig', {'button_label': 'modifier'}) }}<br>

   <center> <button class="btn" style="background-color:gray;border-color: black;color: white"><a href="{{ path('app_maison_index') }}">retourner</a></button></center>

    
{% endblock %}

templates/maison/index.html.twig
{% extends 'front.html.twig' %}

{% block title %}Maison{% endblock %}

{% block body %}
    
    
    
<section class="u-clearfix u-palette-2-base u-section-3" id="carousel_38bf">
<div class="u-clearfix u-sheet u-sheet-1">

    <center><h1> IMMOBILIERS A LOUER </h1></center>


    
    {% for maison in maisons %}
      
      
        <div class="u-border-2 u-border-grey-dark-1 u-container-style u-group u-radius-10 u-shape-round u-white u-group-1">
          <div class="u-container-layout u-container-layout-1">
            <h3 class="u-text u-text-custom-color-1 u-text-default u-text-1"> Immobilier : {{ maison.nomimmob }}</h3><br>
            <h3 class="u-text u-text-default u-text-2">locataire : {{ maison.nomLoy }}</h3><br>
            <h3 class="u-text u-text-default u-text-3">cin du locataire : {{ maison.cinLoy }}</h3><br>
            <h3 class="u-text u-text-default u-text-4">tel du locataire : {{ maison.numerotel }}</h3><br>
            <h3 class="u-text u-text-default u-text-3">prix : {{ maison.prix }} Dt /mois</h3><br>
           <h3 class="u-text u-text-default u-text-3">prochain prix  : {{ maison.prix * 1.05 }} Dt /mois</h3><br>
            <h3 class="u-text u-text-default u-text-4">début contrat :  {{ maison.deb ? maison.deb|date('Y-m-d') : '' }}  </h3><br>
            <h3 class="u-text u-text-default u-text-4">fin contrat :  {{ maison.fin ? maison.fin|date('Y-m-d') : '' }}  </h3><br>
            
            <a href="{{ path('app_maison_edit', {'id': maison.id}) }}" class="u-border-2 u-border-palette-2-base u-btn u-btn-round u-button-style u-hover-palette-2-base u-none u-radius-6 u-text-hover-white u-btn-1">modifier</a>
            {{ include('maison/_delete_form.html.twig') }}
            <a href="{{ path('app_postcom', {'id': maison.id}) }}" class="u-border-2 u-border-palette-2-base u-btn u-btn-round u-button-style u-hover-palette-2-base u-none u-radius-6 u-text-hover-white u-btn-1">consulter payement</a>
          </div>
        </div>
    
    

        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    <br><br>
<center><a href="{{ path('app_maison_new') }}" class="u-border-2 u-border-black u-border-hover-grey-25 u-btn u-btn-round u-button-style u-hover-white u-none u-radius-50 u-btn-3">nouveau immobilier</a></center>
 <br><br>
     <section class="aaaa u-clearfix u-section-1" id="carousel_87ce">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-expanded-width u-list u-list-1">
          <div class="u-repeater u-repeater-1">
            <div class="u-align-center u-container-style u-list-item u-repeater-item u-white u-list-item-1">
              <div class="u-container-layout u-similar-container u-valign-middle u-container-layout-1">
              
                <h3 class="u-custom-font u-font-oswald u-text u-text-palette-2-base u-text-1" data-animation-name="counter" data-animation-event="scroll" data-animation-duration="3000">{{nbrprest}}</h3>
                <h6 class="u-custom-font u-font-oswald u-text u-text-default u-text-palette-2-base u-text-2">nbr d' immobiliers</h6>
              </div>
            </div>
            <div class="u-align-center u-container-style u-list-item u-repeater-item u-white u-list-item-2">
              <div class="u-container-layout u-similar-container u-valign-middle u-container-layout-2">
                <h3 class="u-custom-font u-font-oswald u-text u-text-palette-2-base u-text-3" data-animation-name="counter" data-animation-event="scroll" data-animation-duration="3000">{{gain -( gain * 0.15 ) }} Dt</h3>
                <h6 class="u-custom-font u-font-oswald u-text u-text-default u-text-palette-2-base u-text-4"> revenu globale net pour cette année(avec impot)</h6>
              
              <div class="u-align-center u-container-style u-list-item u-repeater-item u-white u-list-item-2">
              <div class="u-container-layout u-similar-container u-valign-middle u-container-layout-2">
                <h3 class="u-custom-font u-font-oswald u-text u-text-palette-2-base u-text-3" data-animation-name="counter" data-animation-event="scroll" data-animation-duration="3000">{{(gain * 1.05) * (1 - 0.15 )}} Dt</h3>
                <h6 class="u-custom-font u-font-oswald u-text u-text-default u-text-palette-2-base u-text-4">revenu globale net pour la prochaine année(avec impot)</h6>
              </div></div>
            </div>
          </div>
        </div>
      </div>
    </section>
{% endblock %}

templates/maison/new.html.twig
{% extends 'front.html.twig' %}

{% block title %}New Maison{% endblock %}


{% block body %}
<section class="u-clearfix u-palette-2-base u-section-3" id="carousel_38bf">
    <h1>Create new Maison</h1>

    {{ include('maison/_form.html.twig') }}
<br>
   <center><button class="btn" style="background-color:gray;border-color: black;color: white"> <a href="{{ path('app_maison_index') }}">retourner</a></button> </center>
{% endblock %}

templates/maison/new1.html.twig
{% extends 'front.html.twig' %}

{% block title %}Maison{% endblock %}

{% block body %}
<section class="u-clearfix u-palette-2-base u-section-3" id="carousel_38bf">
      <div class="u-clearfix u-sheet u-sheet-1">
      {{ include('payement/_form.html.twig') }}
						
						<button class="u-border-2 u-border-black u-border-hover-grey-25 u-btn u-btn-round u-button-style u-hover-white u-none u-radius-50 u-btn-3"><a href="{{ path('app_postcom', {'id': maison.id})}}">retourner</a></button>
					</div>
                    </section>
                    {% endblock %}

templates/maison/packItem.html.twig
{% extends 'front.html.twig' %}

{% block title %}Maison{% endblock %}

{% block body %}
    
    <section class="u-clearfix u-palette-2-base u-section-3" id="carousel_38bf">
      <div class="u-clearfix u-sheet u-sheet-1">
      
        <div class="u-border-2 u-border-grey-dark-1 u-container-style u-group u-radius-10 u-shape-round u-white u-group-1">
          <div class="u-container-layout u-container-layout-1">
            <h3 class="u-text u-text-custom-color-1 u-text-default u-text-1"> Immobilier : {{ maison.nomimmob }}</h3><br>
            <h3 class="u-text u-text-default u-text-2"> nom du locataire : {{ maison.nomLoy }}</h3><br>
            <h3 class="u-text u-text-default u-text-3">cin du locataire : {{ maison.cinLoy }}</h3><br>
            <h3 class="u-text u-text-default u-text-4">tel du locataire : {{ maison.numerotel }}</h3><br>
            
            <h3 class="u-text u-text-default u-text-4">début contrat :  {{ maison.deb ? maison.deb|date('Y-m-d') : '' }}  </h3><br>
            <h3 class="u-text u-text-default u-text-4">fin contrat :  {{ maison.fin ? maison.fin|date('Y-m-d') : '' }}  </h3><br>
            
            
          </div>
        </div>
        <br><br>
        <section class="u-clearfix u-section-4" id="carousel_87ce">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-expanded-width u-table u-table-responsive u-table-1">
          <table class="u-table-entity">
            <colgroup>
              <col width="25%">
              <col width="25%">
              <col width="25%">
              <col width="25%">
            </colgroup>
            <thead class="u-black u-table-header u-table-header-1">
              <tr style="height: 82px;">
                <th class="u-border-1 u-border-black u-palette-2-base u-table-cell u-table-cell-1">Mois </th>
                <th class="u-border-1 u-border-grey-90 u-palette-2-base u-table-cell u-table-cell-2">Montant </th>
                <th class="u-border-1 u-border-black u-palette-2-base u-table-cell u-table-cell-3">Payement </th>
                <th class="u-border-1 u-border-black u-palette-2-base u-table-cell u-table-cell-4">modifier </th>
                <th class="u-border-1 u-border-black u-palette-2-base u-table-cell u-table-cell-4">supprimer </th>
              </tr>
            </thead>
        
        <tbody class="u-table-body">
              
        {% for payement in payements %}
        
           <tr style="height: 50px;">
                <td class="u-border-1 u-border-grey-30 u-table-cell">{{ payement.mois ? payement.mois|date('Y-m') : '' }}</td>
                <td class="u-border-1 u-border-grey-30 u-table-cell">{{ maison.prix }} Dt</td>
                <td class="u-border-1 u-border-grey-30 u-table-cell">{{ payement.paye }}</td>
                <td class="u-border-1 u-border-grey-30 u-table-cell"><center><a href="{{ path('app_payement_edit', {'id': payement.id})}}" class="u-border-2 u-border-black u-border-hover-grey-25 u-btn u-btn-round u-button-style u-hover-white u-none u-radius-50 u-btn-3"> modifier </a></td>
                <td class="u-border-1 u-border-grey-30 u-table-cell"><center>{{ include('payement/_delete_form.html.twig') }}</td>
              </tr>
              
        {% else %}
            <tr>
            <tr style="height: 50px;">
                <td class="u-border-1 u-border-grey-30 u-table-cell">no records found</td>
                
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <br>
   <center> <button class="u-border-2 u-border-black u-border-hover-grey-25 u-btn u-btn-round u-button-style u-hover-white u-none u-radius-50 u-btn-3"><a href="{{ path('app_postcom1', {'id': maison.id})}}">nouveau payement</a></button></center>

    <section class="aaaa u-clearfix u-section-1" id="carousel_87ce">
<center><button class="u-border-2 u-border-black u-border-hover-grey-25 u-btn u-btn-round u-button-style u-hover-white u-none u-radius-50 u-btn-3"><a href={{asset("/maison")}}>retourner</a></button></center>
    <section class="aaaa u-clearfix u-section-1" id="carousel_87ce">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-expanded-width u-list u-list-1">
          <div class="u-repeater u-repeater-1">
            <div class="u-align-center u-container-style u-list-item u-repeater-item u-white u-list-item-1">
              <div class="u-container-layout u-similar-container u-valign-middle u-container-layout-1">
              
                <h3 class="u-custom-font u-font-oswald u-text u-text-palette-2-base u-text-1" data-animation-name="counter" data-animation-event="scroll" data-animation-duration="3000">{{a}} / {{ nbrprest }}</h3>
                <h6 class="u-custom-font u-font-oswald u-text u-text-default u-text-palette-2-base u-text-2">nbr de mois payés</h6>
              </div>
            </div>
            <div class="u-align-center u-container-style u-list-item u-repeater-item u-white u-list-item-2">
              <div class="u-container-layout u-similar-container u-valign-middle u-container-layout-2">
                <h3 class="u-custom-font u-font-oswald u-text u-text-palette-2-base u-text-3" data-animation-name="counter" data-animation-event="scroll" data-animation-duration="3000">{{a * maison.prix }} Dt</h3>
                <h6 class="u-custom-font u-font-oswald u-text u-text-default u-text-palette-2-base u-text-4">Montant</h6>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    
{% endblock %}

    

templates/maison/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Maison{% endblock %}

{% block body %}
    <h1>Maison</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ maison.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ maison.nom }}</td>
            </tr>
            <tr>
                <th>Nom_loy</th>
                <td>{{ maison.nomLoy }}</td>
            </tr>
            <tr>
                <th>Cin_loy</th>
                <td>{{ maison.cinLoy }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_maison_index') }}">back to list</a>

    <a href="{{ path('app_maison_edit', {'id': maison.id}) }}">edit</a>

    {{ include('maison/_delete_form.html.twig') }}
{% endblock %}